### ISSUE TITLE
Create minimal sample content for an application

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#22]

**Comment by dmundra** [comment]
Based on https://github.com/GSA/open-product-accessibility-template/issues/3#issuecomment-881735339 example content to work with is:

```
title: Drupal Accessibility Conformance Report
name-product-version: Drupal 9.1
product-description: Content Management System
contact-information: mike.gifford@civicactions.com
notes: Links to the issues identified are included where possible to ensure that this is a living document where outstanding issues are regularly reviewed for compliance. The Authoring tool is evaluated against ATAG 2.0, Part A and B. Incorporating feedback from the Drupal community.
chapters:
  - num: "1"
    criteria:
      - num: "1.1.1"
        components:
          - name: "web"
            adherence:
              level: "supports"
              notes: Drupal 8 requires alt text for images by default.
          - name: "electronic-docs"
            adherence:
              level: "supports"
              notes: Some non-textual content in the documentation does not provide a textual alternative.
          - name: "software"
            adherence:
              level: "not-applicable"
          - name: "authoring-tool"
            adherence:
              level: "supports"
              notes: The back end of Drupal Core was built to be  WCAG 2.0 AA compliant and non-text content in the administration interface has a textual equivalent. Audio and video can be added to the media library, but Core does not provide tools to manage transcripts and captions/subtitles for local video and audio - Drupal issue #3002770.
      - num: "1.2.2"
        components:
          - name: "web"
            adherence:
              level: partially-supports
              notes: Authors can satisfy 1.2.1 Audio-only and Video-only (Prerecorded) by using text on the same page.
          - name: "electronic-docs"
            adherence:
              level: partially-supports
              notes: This is not explicitly defined in the documentation.
          - name: "software"
            adherence:
              level: not-applicable
          - name: "authoring-tool"
            adherence:
              level: does-not-support
              notes: There is no additional support for authors within the authoring interface to explain how this can be done.
```
