### ISSUE TITLE
Define minimal schema for content containing top-level metadata

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#4]

**Comment by mgifford** [comment]
Just to confirm, this is the top-level metadata, right? What would we want to add to this? 

```
  # Commissioner / Software vendor 
  # Who is commissioning the evaluation, holds the repository and is ultimately legally responsible for the statement
  - commissioner: 
    - name: 
    - address:
    - corporate-website:
    - repository-url: 
    - legal-notice: 

  # Creator / Reviewer
  # Individual or agency which reviews the software or service
  - dct:creator:
    - name: 
      - agency: 
      - email: 
      - reviewer-legal-statement: 
```

**Comment by dmundra** [comment]
I think I got this in #3. Here is a snippet of the top-level items without chapters:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "opat.schema.json",
  "title": "OPAT",
  "description": "Open Product Accessibility Template (OPAT) as a YAML file.",
  "type": "object",
  "properties": {
    "title": {
      "description": "The title of the report in the heading format of '[Company Name] Accessibility Conformance Report'.",
      "type": "string"
    },
    "name-product-version": {
      "description": "Product name and version if available.",
      "type": "string"
    },
    "product-description": {
      "description": "A brief description of the product.",
      "type": "string"
    },
    "contact-information": {
      "description": "Primary contact email.",
      "type": "string"
    },
    "notes": {
      "description": "Any details or explanation about the product or the report.",
      "type": "string"
    },
  },
  "required": [
    "title",
    "name-product-version",
    "product-description",
    "contact-information"
  ]
}
```

Example content:

```
title: Drupal Accessibility Conformance Report
name-product-version: Drupal 9.1
product-description: Content Management System
contact-information: mike.gifford@civicactions.com
notes: Links to the issues identified are included where possible to ensure that this is a living document where outstanding issues are regularly reviewed for compliance. The Authoring tool is evaluated against ATAG 2.0, Part A and B. Incorporating feedback from the Drupal community.
```

Do we need more structure for this one? Maybe have contact information follow a standard 'contact' scheme that can be applied to the commissioner as well.

**Comment by dmundra** [comment]
We expand the product section into an object. E.g.

```
product:
  name: Drupal
  version: "9.1"
  description: Content Management System
```

Maybe that does make the case now for contact information to be split as well. Is that detail needed?
