### ISSUE TITLE
Optional fields to capture product, developer, vendor, author etc

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#66]
Need to flesh out what the needs and data structure here is, but could be good to capture name, URL, contact info etc for the product, developer, vendor and the VPAT author(s).

**Comment by mgifford** [comment]
Moving Owen's lists into lists so they are easier to read. 

There is the URL of the project but also the URL of the repository that contains the OPAT.  For instance, with Drupal, it might be somewhere like https://git.drupalcode.org/project/opat-en.yaml

Would also be useful to just outline how one would add optional fields if a department wanted to add additional metadata for their own internal use.

**Comment by mgifford** [comment]
So if we want to include issue queues, we might want to consider switching from:

```
          - name: "authoring-tool"
            adherence:
              level: "supports"
              notes: Generally parsing is very well supported, but there are a few places where this needs to be improved - Drupal issue 1852090 and 3144948.
```

to one that allows an array of links. From this the system could draw out the title or other data such as last updated date if it were available. 

```
          - name: "authoring-tool"
            adherence:
              level: "supports"
              notes: Generally parsing is very well supported, but there are a few places where this needs to be improved
              issue_url: 
                https://www.drupal.org/node/1852090
                https://www.drupal.org/node/3144948
```

I'd also like to see a repository link up at the top so we can possibly update:

```
product:
  name: Drupal
  version: "9.1"
  description: Content Management System
```

to include

```
product:
  name: Drupal
  version: "9.1"
  description: Content Management System
  repository_yaml: https://github.com/GSA/open-product-accessibility-template/blob/main/opat/drupal-9.yaml
  repository_source: https://github.com/GSA/open-product-accessibility-template.git
```

Might also be useful to have repository_markdown & repository_html fields as optional.
