### ISSUE TITLE
Adding Notes to Tables & Chapters

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#85]
I'd like to be able to add a note for each chapter like this:

```
chapters:
  success_criteria_level_a:
    notes: "Drupal doesn't make a strong distinction between the front-end & back-end accessibility. Many administration interfaces can be exposed to users in a more interactive site. Generally, this report focuses on the Conformance Level / Remarks and Explanations so that Web comments are about elements that are typically public, while Authoring Tool is typically for authors and administrators. The goal of the authoring interface is to support ATAG 2.0 AA (Part A and B).

The Drupal community strives to keep up with the latest WCAG recommendation."
    criteria:
      - num: "1.1.1"
```
